language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt

script:
  - python -m  unittest discover -s  ./src/Tests

branches:
  only:
    - master
    - Project_2

env:
  - PYTHONPATH="${PYTHONPATH}:/src/Calculator:/src/CsvReader:/src/Statistics:/src/Tests:/src"