language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt

env:
  - PYTHONPATH="${PYTHONPATH}:/src/Calculator:/src/CsvReader:/src/Statistics:/src/Tests:/src"

branches:
  only:
    - master
    - Project_2

